### ISSUE TITLE
No output directory when mounting volume

### ISSUE THREAD

**Issue by argideritzalpea** [LiyuanLucasLiu/ArabicNER#1]
~/ArabicNER$ nvidia-docker run -v ``pwd''/data:/data:ro -v <Output Path>:/wdata -it arabic_ner

-bash: Output: No such file or directory

**Comment by LiyuanLucasLiu** [comment]
You need to use -v FOLDER_PATH:TARGET_FOLDER_PATH. For example, you can use:
```
nvidia-docker run -v /home/user/data:/data:ro -v /home/user/wdata:/wdata -it arabic_ner
```
For more information, please check https://www.docker.com/why-docker
